// APP
export const APP_RESET = 'APP_RESET';

// USER
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const AUTHENTICATING_USER = 'AUTHENTICATING_USER';
export const LOGIN_USER= 'LOGIN_USER';
export const UPDATE_USER= 'UPDATE_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const UPDATE_USER_LOGIN = 'UPDATE_USER_LOGIN';


// MATCHES
export const UPDATE_MATCHES = 'UPDATE_MATCHES';
export const FETCHING_MATCHES = 'FETCHING_MATCHES';
export const SHOW_REFRESHING_MATCHES = 'SHOW_REFRESHING_MATCHES';


// MATCH
export const SELECT_MATCH = 'SELECT_MATCH';
export const VERIFY_ANSWER = 'VERIFY_ANSWER';


// MATCH CHAT
export const UPDATE_MATCH_CHAT_INPUT_VALUE = 'UPDATE_MATCH_CHAT_INPUT_VALUE';
export const CLEAR_MATCH_CHAT_INPUT_VALUE = 'CLEAR_MATCH_CHAT_INPUT_VALUE';
export const UPDATE_MATCH_CHAT_LAST_ACTIVITY = 'UPDATE_MATCH_CHAT_LAST_ACTIVITY';


// MATCH ALERT
export const SHOW_MATCH_ALERT = 'SHOW_MATCH_ALERT';
export const SHOW_QUIT_MATCH_ALERT = 'SHOW_QUIT_MATCH_ALERT';
export const SHOW_PENDING_MATCH_ALERT = 'SHOW_PENDING_MATCH_ALERT';
export const HIDE_MATCH_ALERT = 'HIDE_MATCH_ALERT';


// LAYOUT
export const SHOW_CREATE_MATCH = 'SHOW_CREATE_MATCH';
export const HIDE_CREATE_MATCH = 'HIDE_CREATE_MATCH';
export const SHOW_USER_DRAWER = 'SHOW_USER_DRAWER';
export const HIDE_USER_DRAWER = 'CLOSE_USER_DRAWER';
export const SHOW_MATCHES = 'SHOW_MATCHES';
export const HIDE_MATCHES = 'CLOSE_MATCHES';
export const SHOW_MATCH_CHAT = 'SHOW_MATCH_CHAT';
export const HIDE_MATCH_CHAT = 'CLOSE_MATCH_CHAT';
export const SHOW_SEARCH = 'SHOW_SEARCH';
export const HIDE_SEARCH = 'CLOSE_SEARCH';


// SEARCH
export const FETCH_SEARCH = 'FETCH_SEARCH';
export const CLEAR_SEARCH_INPUT_VALUE = 'CLEAR_SEARCH_INPUT_VALUE';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
export const CLEAR_SEARCH_SELECTED_RESULT = 'CLEAR_SEARCH_SELECTED_RESULT';
export const UPDATE_SEARCH_INPUT_VALUE = 'UPDATE_SEARCH_INPUT_VALUE';
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
export const UPDATE_SEARCH_SELECTED_RESULT = 'UPDATE_SEARCH_SELECTED_RESULT';


// WEBSOCKET
export const UPDATE_WEBSOCKET = 'UPDATE_WEBSOCKET';
