// USER
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const AUTHENTICATING_USER = 'AUTHENTICATING_USER';
export const LOGIN_USER= 'LOGIN_USER';
export const UPDATE_USER= 'UPDATE_USER';
export const CLEAR_USER= 'CLEAR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const UPDATE_USER_LOGIN = 'UPDATE_USER_LOGIN';

// MATCHES
export const UPDATE_MATCHES = 'UPDATE_MATCHES';
export const FETCHING_MATCHES = 'FETCHING_MATCHES';
export const SHOW_REFRESHING_MATCHES = 'SHOW_REFRESHING_MATCHES';
export const HIDE_REFRESHING_MATCHES = 'HIDE_REFRESHING_MATCHES';
export const SHOW_PENDING_MATCH_ALERT = 'SHOW_PENDING_MATCH_ALERT';
export const HIDE_PENDING_MATCH_ALERT = 'HIDE_PENDING_MATCH_ALERT';

// MATCH
export const UPDATE_MATCH = 'UPDATE_MATCH';
export const FETCH_MATCH = 'FETCH_MATCH';
export const SHOW_REFRESHING_MATCH = 'SHOW_REFRESHING_MATCH';
export const HIDE_REFRESHING_MATCH = 'HIDE_REFRESHING_MATCH';
export const REFRESH_MATCH = 'REFRESH_MATCH';
export const VERIFY_ANSWER = 'VERIFY_ANSWER';
export const SHOW_QUIT_MATCH_ALERT = 'SHOW_QUIT_MATCH_ALERT';
export const HIDE_QUIT_MATCH_ALERT = 'HIDE_QUIT_MATCH_ALERT';
export const SHOW_MATCH_ALERT = 'SHOW_MATCH_ALERT';
export const HIDE_MATCH_ALERT = 'HIDE_MATCH_ALERT';
export const UPDATE_MATCH_CHAT_INPUT_VALUE = 'UPDATE_MATCH_CHAT_INPUT_VALUE';
export const CLEAR_MATCH_CHAT_INPUT_VALUE = 'CLEAR_MATCH_CHAT_INPUT_VALUE';
export const UPDATE_MATCH_CHAT_LAST_ACTIVITY = 'UPDATE_MATCH_CHAT_LAST_ACTIVITY';


// LAYOUT
export const SHOW_USER_DRAWER = 'SHOW_USER_DRAWER';
export const HIDE_USER_DRAWER = 'CLOSE_USER_DRAWER';
export const SHOW_MATCHES = 'SHOW_MATCHES';
export const HIDE_MATCHES = 'CLOSE_MATCHES';
export const SHOW_MATCH_CHAT = 'SHOW_MATCH_CHAT';
export const HIDE_MATCH_CHAT = 'CLOSE_MATCH_CHAT';

// SEARCH
export const FETCH_SEARCH = 'FETCH_SEARCH';

// SEARCH MOVIE
export const SELECT_MOVIE_SEARCH_RESULT = 'SELECT_MOVIE_SEARCH_RESULT';
export const CLEAR_MOVIE_SEARCH_RESULT = 'CLEAR_MOVIE_SEARCH_RESULT';
export const UPDATE_MOVIE_SEARCH_VALUE = 'UPDATE_MOVIE_SEARCH_VALUE';
export const CLEAR_MOVIE_SEARCH_VALUE = 'CLEAR_MOVIE_SEARCH_VALUE';
export const UPDATE_MOVIE_SEARCH_RESULTS = 'UPDATE_MOVIE_SEARCH_RESULTS';
export const CLEAR_MOVIE_SEARCH_RESULTS = 'CLEAR_MOVIE_SEARCH_RESULTS';

// SEARCH USER
export const SELECT_USER_SEARCH_RESULT = 'SELECT_USER_SEARCH_RESULT';
export const CLEAR_USER_SEARCH_RESULT = 'CLEAR_USER_SEARCH_RESULT';
export const UPDATE_USER_SEARCH_VALUE = 'UPDATE_USER_SEARCH_VALUE';
export const CLEAR_USER_SEARCH_VALUE = 'CLEAR_USER_SEARCH_VALUE';
export const UPDATE_USER_SEARCH_RESULTS = 'UPDATE_USER_SEARCH_RESULTS';
export const CLEAR_USER_SEARCH_RESULTS = 'CLEAR_USER_SEARCH_RESULTS';

// SEARCH ACTOR
export const SELECT_ACTOR_SEARCH_RESULT = 'SELECT_ACTOR_SEARCH_RESULT';
export const CLEAR_ACTOR_SEARCH_RESULT = 'CLEAR_ACTOR_SEARCH_RESULT';
export const UPDATE_ACTOR_SEARCH_VALUE = 'UPDATE_ACTOR_SEARCH_VALUE';
export const CLEAR_ACTOR_SEARCH_VALUE = 'CLEAR_ACTOR_SEARCH_VALUE';
export const UPDATE_ACTOR_SEARCH_RESULTS = 'UPDATE_ACTOR_SEARCH_RESULTS';
export const CLEAR_ACTOR_SEARCH_RESULTS = 'CLEAR_ACTOR_SEARCH_RESULTS';

// WEBSOCKET
export const UPDATE_WEBSOCKET = 'UPDATE_WEBSOCKET';
